### ISSUE TITLE
[Question] - Why is master build tagged with beta

### ISSUE THREAD

**Issue by dazinator** [GitTools/GitTools.Core#44]
From the gitconfig yaml:

```
assembly-versioning-scheme: MajorMinorPatch
next-version: 1.0.0
branches:
  master:
    tag: 'beta'
```

I don't understand why master branch is setup to produce beta packages - I'm going to remove unless someone can clarify..
